<?php

namespace MainBundle\Repository;

/**
 * Avis_evenementRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Avis_evenementRepository extends \Doctrine\ORM\EntityRepository
{
}
