<?php

namespace MainBundle\Repository;

/**
 * Avis_espaceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Avis_espaceRepository extends \Doctrine\ORM\EntityRepository
{
}
