<?php

namespace MainBundle\Repository;

/**
 * Commentaire_forumRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Commentaire_forumRepository extends \Doctrine\ORM\EntityRepository
{
}
