<?php

namespace MainBundle\Repository;

/**
 * MessageRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MessageRepository extends \Doctrine\ORM\EntityRepository
{
    public function fetchMessages($user,$touser,$last)
    {
        $users = array($user,$touser);
        $qb = $this->createQueryBuilder('m');
        $qb->andWhere("m.receiver in (:ur)")->setParameter(":ur",$users);
        $qb->andWhere("m.sender in (:us)")->setParameter(":us",$users);
        $qb->orderBy("m.date","ASC");
        if($last != 0)
            $qb->andWhere("m.id > :la")->setParameter(":la",$last);
        return $qb->getQuery()->execute();
    }
}
