<?php

namespace MainBundle\Repository;

/**
 * Participation_evenementRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Participation_evenementRepository extends \Doctrine\ORM\EntityRepository
{
}
