<?php

namespace MainBundle\Repository;

/**
 * Photo_espaceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Photo_espaceRepository extends \Doctrine\ORM\EntityRepository
{
}
