profil_homepage:
    path:     /journal
    defaults: { _controller: ProfilBundle:Profil:index }

paramInfo:
    path:     /parametres
    defaults: { _controller: ProfilBundle:Profil:paramsInfo }

album:
    path:     /album
    defaults: { _controller: ProfilBundle:Profil:album }

apropos:
    path:     /apropos
    defaults: { _controller: ProfilBundle:Profil:Apropos }

listphoto:
    path:     /listphoto
    defaults: { _controller: ProfilBundle:Profil:listPhoto }

centreinteret:
    path:     /centreinteret
    defaults: { _controller: ProfilBundle:Profil:centreint }